CREATE TABLE IF NOT EXISTS hubspot_installs (
  id SERIAL PRIMARY KEY,
  app_id SMALLINT NOT NULL UNIQUE,
  portal_id VARCHAR(255) NOT NULL UNIQUE,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hubspot_apps (
  id SERIAL PRIMARY KEY,
  app_id SMALLINT NOT NULL UNIQUE,
  client_id VARCHAR(100) NOT NULL UNIQUE,
  client_secret VARCHAR(100) NOT NULL UNIQUE,
  install_url TEXT,
  redirect_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_hubspot_apps_app_id ON hubspot_apps(app_id);
